
/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

public class ReportModel {

    private int stockLimit;
    private String reportName;

    public void setStockLimit(int stockLimit) {
        this.stockLimit = stockLimit;
    }

    public int getStockLimit() {
        return this.stockLimit;
    }
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }

    public String getReportName() {
        return this.reportName;
    }
}
