package ${packageName}.model;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
<#assign classbody>
public class ${serviceId?cap_first}ReportModel {

<#list properties?keys as key>
<#assign propertyName = key>
<#assign propertyType = properties[key]>
	private ${propertyType} ${propertyName};
</#list>

<#list properties?keys as key>
<#assign propertyName = key>
<#assign propertyType = properties[key]>
<#assign methodSignatureProperty = propertyName?cap_first>
	public void set${methodSignatureProperty}(${propertyType} ${propertyName}) {
		this.${propertyName} = ${propertyName};
	}

	public ${propertyType} get${methodSignatureProperty}() {
		return this.${propertyName};
	}
</#list>
}
</#assign>
${classbody}